### ISSUE TITLE
Jellyfin not starting proparly

### ISSUE THREAD

**Issue by 2Wanderer** [jeppevinkel/jellyfin-tizen-builds#19]
I just installed the latest version 2023-11-05 to an UE32N5300 Tizen SmartTv. Installation went succesfull, app started, been greeted by the logo, but then just displays a black screen, and thats about it. I was able to close te app and return to the menu

**Comment by jeppevinkel** [comment]
I see the same issue and will investigate a bit.

That's for the link @Tntdruid I didn't know someone made such a tool :)

**Comment by jeppevinkel** [comment]
I assumed this was due to changes I made yesterday, but I found the same issue on the jellyfin-web repo, so I'll watch that thread and close this if they make a fix that also fixes it on my builds. For now, just install the normal or prerelease versions as I have tested those to work on my TV. https://github.com/jellyfin/jellyfin-web/issues/4940

**Comment by Bartel-C8** [comment]
This was probably fixed with this merge:
https://github.com/jellyfin/jellyfin-web/pull/4973

But the release from this repo is older than that merge...

But there is still an other issue, https://github.com/jellyfin/jellyfin-web/pull/4973#issuecomment-1807019465 , which is possibly solved here: https://github.com/jellyfin/jellyfin-web/pull/4995

But not yet merged... Would it be possible to create a new release once that is fixed?

**Comment by jeppevinkel** [comment]
Closing this since the builds currently work.
