### ISSUE TITLE
Media stop playing, server unavailable

### ISSUE THREAD

**Issue by makakam83** [jeppevinkel/jellyfin-tizen-builds#37]
Hi

With the latest 10.9.1 release and the latest jeppevinkel build(Thanks a lot for your work!) my Tizen app has stopped playing a couple of times now and when it does the server seems to be stalled and can not be accessed until I restart the container. Anyone has the same issue? It did not happen even once before the update.

Can't  find any info in logs related to it.

**Comment by smartmuel** [comment]
I had this issue with my container running jellyfin 10.9.1. but I had a very old Tizen app... I saw that my container didn't do hardware transcoding to the h.265 movie I ran ( it did work through the browser ) and after few seconds the Tizen froze and the container was 'unhealthy' and I needed to restart it.
I thought the old Tizen app was the issue but now I have another issue that is already open the "failed to construct 'Headers'".

**Comment by jeppevinkel** [comment]
Issues related to 10.9.z are better suited in the respective jellyfin-tizen and jellyfin-web repositories since my builds are using their code directly and built according to their instructions. I don't think I can do anything until they provide a fix since I'm not affiliated with Jellyfin in any way. I only provide builds of their code.

My recommendation would be to stay on 10.8.z for a few weeks since 10.9.z is still so new I would expect bugs and issues. Especially on Tizen since it appears to be a low priority from Jellyfin and they rarely make any updates to it.
